sdk: '2'
language: bash
go-runtime:
  version: '1.12-alpine'
native:
  image: 'openjdk:8u181-jre-alpine'
  static:
      - path: native.sh
        dest: native
  build:
    image: 'openjdk:8u181-slim'
    deps:
      - 'apt-get update && apt-get install -y make bash wget gradle'
    run:
      - 'make'
      - 'gradle shadowJar'
    artifacts:
      - path: '/native/build/libs/native-jar-with-dependencies.jar'
  test:
    run:
        - 'gradle test --info --stacktrace'
