name = "Bash"
language = "bash"
aliases = ["shell"]
status = "beta"
features = ["ast","uast","roles"]

[documentation]
description  = """
bash driver for [babelfish](https://github.com/bblfsh/bblfshd).
"""
