// Package intellij contains the bblfsh predicates we want to look for
// in ASTs generated by the Intellij BashSupport module, which are based
// on constants defined in that library.
package intellij

import . "gopkg.in/bblfsh/sdk.v0/uast/ann"

var (
	File               = HasInternalType("FILE")
	Comment            = HasInternalType("[Bash] Comment")
	Shebang            = HasInternalType("[Bash] shebang element")
	VarDefElement      = HasInternalType("var-def-element")
	AssignmentWord     = HasInternalType("[Bash] assignment_word")
	FunctionDefElement = HasInternalType("function-def-element")
	Function           = HasInternalType("[Bash] function")
	NamedSymbol        = HasInternalType("[Bash] named symbol")
	GroupElement       = HasInternalType("group element")
	IfShellCommand     = HasInternalType("if shellcommand")
	ForShellCommand    = HasInternalType("for shellcommand")
	WhileLoop          = HasInternalType("while loop")
	UntilLoop          = HasInternalType("until loop")
)
